# Generated by Django 6.1 on 2026-08-21 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MonitoringEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monitoring_employee',
            },
        ),
        migrations.CreateModel(
            name='RepresentativeEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('products', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'representative_employee',
            },
        ),
        migrations.CreateModel(
            name='StaffEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff_employee',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(default='N/A', max_length=255)),
                ('contact_person', models.CharField(default='N/A', max_length=255, unique=True)),
                ('contact_title', models.CharField(default='N/A', max_length=255)),
                ('address', models.TextField(default='N/A')),
                ('city', models.CharField(default='N/A', max_length=255)),
                ('postal_code', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(default='N/A', max_length=255)),
                ('phone_number', models.CharField(default='N/A', max_length=255)),
                ('fax', models.CharField(default='N/A', max_length=255)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discontinued', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('low_stock_value', models.IntegerField(default=10)),
                ('category', models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.PROTECT, related_name='finished_products', to='master_data.category', to_field='name')),
            ],
            options={
                'db_table': 'finished_products_static',
            },
        ),
        migrations.CreateModel(
            name='FinishedProductWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warehouse', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_product', models.ForeignKey(db_column='finished_product_id', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='master_data.finishedproduct')),
            ],
            options={
                'db_table': 'finished_products_warehouses',
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discontinued', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('low_stock_value', models.IntegerField(default=10)),
                ('category', models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.PROTECT, related_name='packaging_items', to='master_data.category', to_field='name')),
                ('supplier', models.ForeignKey(db_column='supplier_contact', on_delete=django.db.models.deletion.PROTECT, related_name='packaging_items', to='master_data.supplier', to_field='contact_person')),
            ],
            options={
                'db_table': 'packaging_static',
            },
        ),
        migrations.CreateModel(
            name='PackagingWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warehouse', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packaging', models.ForeignKey(db_column='packaging_id', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='master_data.packaging')),
            ],
            options={
                'db_table': 'packaging_warehouses',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discontinued', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('low_stock_value', models.IntegerField(default=10)),
                ('category', models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='master_data.category', to_field='name')),
                ('supplier', models.ForeignKey(db_column='supplier_contact', on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='master_data.supplier', to_field='contact_person')),
            ],
            options={
                'db_table': 'raw_materials_static',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warehouse', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_material', models.ForeignKey(db_column='raw_material_id', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='master_data.rawmaterial')),
            ],
            options={
                'db_table': 'raw_materials_warehouses',
            },
        ),
    ]
