# Generated by Django 6.1 on 2026-08-22 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='supplier',
            field=models.ForeignKey(db_column='supplier_company_name', on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='master_data.supplier', to_field='company_name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
